all_joints:
- - 0
- - 1
- - 2
- - 3
- - 4
- - 5
- - 6
- - 7
- - 8
- - 9
- - 10
- - 11
- - 12
- - 13
- - 14
- - 15
- - 16
- - 17
- - 18
- - 19
- - 20
- - 21
- - 22
- - 23
- - 24
- - 25
- - 26
all_joints_names:
- nose
- left_ear
- right_ear
- left_ear_tip
- right_ear_tip
- left_eye
- right_eye
- neck
- mid_back
- mouse_center
- mid_backend
- mid_backend2
- mid_backend3
- tail_base
- tail1
- tail2
- tail3
- tail4
- tail5
- left_shoulder
- left_midside
- left_hip
- right_shoulder
- right_midside
- right_hip
- tail_end
- head_midpoint
dataset: training-datasets/iteration-0/UnaugmentedDataSet_ma_supertopviewMarch30/ma_supertopview_maDLC_scorer95shuffle1.pickle
dataset_type: multi-animal-imgaug
global_scale: 0.8
init_weights: /mnt/md0/shaokai/DeepLabCut/deeplabcut/pose_estimation_tensorflow/models/pretrained/resnet_v1_50.ckpt
location_refinement: true
locref_smooth: false
locref_stdev: 7.2801
minconfidence: 0.01
multi_stage: true
net_type: resnet_50
nmsradius: 5.0
num_idchannel: 0
num_joints: 27
num_limbs: 351
pairwise_predict: false
partaffinityfield_graph:
partaffinityfield_predict: false
scoremap_dir: test
sigma: 1
batch_size: 8
gradient_masking: true
