all_joints:
- - 0
- - 1
- - 2
- - 3
- - 4
- - 5
- - 6
- - 7
- - 8
- - 9
- - 10
- - 11
- - 12
- - 13
- - 14
- - 15
- - 16
- - 17
- - 18
- - 19
- - 20
- - 21
- - 22
- - 23
- - 24
- - 25
- - 26
- - 27
- - 28
- - 29
- - 30
- - 31
- - 32
- - 33
- - 34
- - 35
- - 36
- - 37
- - 38
all_joints_names:
- nose
- upper_jaw
- lower_jaw
- mouth_end_right
- mouth_end_left
- right_eye
- right_earbase
- right_earend
- right_antler_base
- right_antler_end
- left_eye
- left_earbase
- left_earend
- left_antler_base
- left_antler_end
- neck_base
- neck_end
- throat_base
- throat_end
- back_base
- back_end
- back_middle
- tail_base
- tail_end
- front_left_thai
- front_left_knee
- front_left_paw
- front_right_thai
- front_right_knee
- front_right_paw
- back_left_paw
- back_left_thai
- back_right_thai
- back_left_knee
- back_right_knee
- back_right_paw
- belly_bottom
- body_middle_right
- body_middle_left
dataset: training-datasets/iteration-0/UnaugmentedDataSet_ma_superquadrupedMarch30/ma_superquadruped_maDLC_scorer85shuffle1.pickle
dataset_type: multi-animal-imgaug
global_scale: 0.8
init_weights: /mnt/md0/shaokai/DeepLabCut/deeplabcut/pose_estimation_tensorflow/models/pretrained/resnet_v1_50.ckpt
location_refinement: true
locref_smooth: false
locref_stdev: 7.2801
minconfidence: 0.01
multi_stage: true
net_type: resnet_50
nmsradius: 5.0
num_idchannel: 0
num_joints: 39
num_limbs: 741
pairwise_predict: false
partaffinityfield_graph:
partaffinityfield_predict: false
scoremap_dir: test
sigma: 1
batch_size: 8
gradient_masking: true
